import { Send, Loader2, Clock, Filter, ChevronDown, Zap } from "lucide-react";
import {
  WhatsAppTemplate,
  WhatsAppColumn,
  AUTO_GENERATED_TEMPLATES,
  EVENT_TEMPLATES,
  FIXED_TIME_TEMPLATES,
  DYNAMIC_TEMPLATES,
  CRON_EVENT_TEMPLATES,
  COLUMN_FILTER_TEMPLATES,
  WEEKDAYS,
} from "./whatsappTemplateDefaults";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

interface WhatsAppTemplateCardProps {
  tpl: WhatsAppTemplate;
  index: number;
  columns: WhatsAppColumn[];
  sendingTest: string | null;
  onUpdate: (index: number, field: keyof WhatsAppTemplate, value: string | boolean | number | undefined) => void;
  onToggleColumn: (index: number, columnId: string) => void;
  onSendTest: (tpl: WhatsAppTemplate) => void;
}

function getExclusionSummary(tpl: WhatsAppTemplate, columns: WhatsAppColumn[]) {
  if (!tpl.excluded_column_ids?.length) return "Enviando para todas as colunas";
  const names = tpl.excluded_column_ids
    .map((id) => columns.find((c) => c.id === id)?.name)
    .filter(Boolean);
  return `Excluindo: ${names.join(", ")}`;
}

export function WhatsAppTemplateCard({
  tpl,
  index,
  columns,
  sendingTest,
  onUpdate,
  onToggleColumn,
  onSendTest,
}: WhatsAppTemplateCardProps) {
  const isEvent = EVENT_TEMPLATES.includes(tpl.template_type);
  const isCronEvent = CRON_EVENT_TEMPLATES.includes(tpl.template_type);
  const isFixedTime = FIXED_TIME_TEMPLATES.includes(tpl.template_type);
  const isDynamic = DYNAMIC_TEMPLATES.includes(tpl.template_type);
  const hasFilter = COLUMN_FILTER_TEMPLATES.includes(tpl.template_type);
  const isAutoGenerated = AUTO_GENERATED_TEMPLATES.includes(tpl.template_type);

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base">{tpl.label}</CardTitle>
          <Switch
            checked={tpl.is_enabled}
            onCheckedChange={(v) => onUpdate(index, "is_enabled", v)}
          />
        </div>
        <CardDescription className="text-xs">
          {isAutoGenerated ? (
            <span className="text-amber-500">
              ⚡ Mensagem gerada automaticamente pelo sistema (modelo ilustrativo abaixo)
            </span>
          ) : (
            <>Variáveis: {tpl.variables.map((v) => `{{${v}}}`).join(", ")}</>
          )}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <Textarea
          value={tpl.message_template}
          onChange={(e) => onUpdate(index, "message_template", e.target.value)}
          rows={4}
          className="font-mono text-sm"
          readOnly={isAutoGenerated}
          disabled={isAutoGenerated}
        />

        <div className="flex items-center gap-4 flex-wrap">
          {(isEvent || isCronEvent) && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground bg-muted/50 rounded-md px-3 py-1.5">
              <Zap className="h-4 w-4" />
              <span>Disparado automaticamente por evento</span>
            </div>
          )}

          {isFixedTime && tpl.template_type !== "weekly_summary" && (
            <div className="flex items-center gap-2">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <Label className="text-sm text-muted-foreground">Horário:</Label>
              <Input
                type="time"
                value={tpl.send_time}
                onChange={(e) => onUpdate(index, "send_time", e.target.value)}
                className="w-28 h-8 text-sm"
              />
            </div>
          )}

          {tpl.template_type === "weekly_summary" && (
            <>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-muted-foreground" />
                <Label className="text-sm text-muted-foreground">Horário:</Label>
                <Input
                  type="time"
                  value={tpl.send_time}
                  onChange={(e) => onUpdate(index, "send_time", e.target.value)}
                  className="w-28 h-8 text-sm"
                />
              </div>
              <div className="flex items-center gap-2">
                <Label className="text-sm text-muted-foreground">Dia:</Label>
                <Select
                  value={tpl.send_time_2 || "1"}
                  onValueChange={(v) => onUpdate(index, "send_time_2", v)}
                >
                  <SelectTrigger className="w-40 h-8 text-sm">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {WEEKDAYS.map((day) => (
                      <SelectItem key={day.value} value={day.value}>
                        {day.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </>
          )}

          {isDynamic && (
            <>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-muted-foreground" />
                <Label className="text-sm text-muted-foreground">1º Alerta:</Label>
                <Input
                  type="number"
                  min={1}
                  max={168}
                  value={tpl.due_date_hours_before ?? 24}
                  onChange={(e) =>
                    onUpdate(index, "due_date_hours_before", parseInt(e.target.value) || 24)
                  }
                  className="w-20 h-8 text-sm"
                />
                <span className="text-sm text-muted-foreground">horas antes</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-muted-foreground" />
                <Label className="text-sm text-muted-foreground">2º Alerta:</Label>
                <Input
                  type="number"
                  min={0}
                  max={168}
                  value={tpl.due_date_hours_before_2 ?? ""}
                  onChange={(e) => {
                    const val = e.target.value ? parseInt(e.target.value) : undefined;
                    onUpdate(index, "due_date_hours_before_2", val);
                  }}
                  placeholder="Opcional"
                  className="w-20 h-8 text-sm"
                />
                <span className="text-sm text-muted-foreground">horas antes</span>
              </div>
            </>
          )}
        </div>

        {hasFilter && columns.length > 0 && (
          <Collapsible>
            <CollapsibleTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="w-full justify-between text-xs text-muted-foreground h-8"
              >
                <span className="flex items-center gap-1.5">
                  <Filter className="h-3.5 w-3.5" />
                  {getExclusionSummary(tpl, columns)}
                </span>
                <ChevronDown className="h-3.5 w-3.5" />
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent className="pt-2">
              <div className="grid grid-cols-2 gap-2 p-2 border rounded-md">
                {columns.map((col) => (
                  <label key={col.id} className="flex items-center gap-2 text-sm cursor-pointer">
                    <Checkbox
                      checked={tpl.excluded_column_ids?.includes(col.id) || false}
                      onCheckedChange={() => onToggleColumn(index, col.id)}
                    />
                    <span className="truncate">{col.name}</span>
                  </label>
                ))}
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                Marque as colunas que deseja <strong>excluir</strong> do envio.
              </p>
            </CollapsibleContent>
          </Collapsible>
        )}

        <div className="flex justify-end">
          <Button
            size="sm"
            variant="outline"
            onClick={() => onSendTest(tpl)}
            disabled={sendingTest === tpl.template_type}
          >
            {sendingTest === tpl.template_type ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <Send className="h-4 w-4 mr-2" />
            )}
            Enviar Teste
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
